version: "3.9"

services:
  wireguard:
    build: ./services/wireguard-server
    ports:
      # Bitcoin P2p
      - 8333:8333
      # Monero P2P
      - 18080:18080
    volumes:
      - ./mounts/wireguard-server:/etc/wireguard
